import type { LucideIcon } from "lucide-react";
import {
  Award,
  BadgePercent,
  Bell,
  BarChart3,
  BookOpen,
  Bot,
  ClipboardList,
  Compass,
  CreditCard,
  FileInput,
  FileText,
  FolderKanban,
  GraduationCap,
  HelpCircle,
  History,
  Home,
  Inbox,
  LayoutDashboard,
  LibraryBig,
  Mail,
  Megaphone,
  MessageSquare,
  Puzzle,
  Settings,
  Shield,
  Sparkles,
  Tags,
  Ticket,
  TrendingUp,
  User,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";

const ICON_BY_LABEL: Record<string, LucideIcon> = {
  Overview: LayoutDashboard,
  Dashboard: LayoutDashboard,
  Members: Users,
  People: Users,
  "Staff invites": UserPlus,
  Groups: UsersRound,
  Activity: History,
  "Roles & access": Shield,
  Users: Users,
  Courses: BookOpen,
  Programs: FolderKanban,
  Categories: Tags,
  Instructors: GraduationCap,
  Enrollments: GraduationCap,
  Certificates: Award,
  Assessments: ClipboardList,
  "Personality Profile": Compass,
  Revenue: Wallet,
  Payments: Wallet,
  Reports: BarChart3,
  Applications: Inbox,
  Forms: FileInput,
  Tickets: Ticket,
  "Support Tickets": Ticket,
  Announcements: Megaphone,
  Email: Mail,
  Settings: Settings,
};

/** Icon lookup by route prefix — longest match wins at runtime. */
const ICON_BY_PREFIX: [string, LucideIcon][] = [
  ["/admin/members/invites", UserPlus],
  ["/admin/members/groups", UsersRound],
  ["/admin/members/activity", History],
  ["/admin/members/roles", Shield],
  ["/admin/members", Users],
  ["/admin/applications", Inbox],
  ["/admin/programs", FolderKanban],
  ["/admin/syllabus", LibraryBig],
  ["/admin/assignments", ClipboardList],
  ["/admin/quizzes", Puzzle],
  ["/admin/announcements", Megaphone],
  ["/admin/email-templates", Mail],
  ["/admin/forums", MessageSquare],
  ["/admin/badges", Award],
  ["/admin/coupons", BadgePercent],
  ["/admin/offers", Sparkles],
  ["/admin/payments", CreditCard],
  ["/admin/payment-settings", Wallet],
  ["/admin/plugins/ai", Bot],
  ["/admin/forms", FileInput],
  ["/admin/tickets", Ticket],
  ["/admin", LayoutDashboard],
  ["/student/dashboard", Home],
  ["/student/enroll", GraduationCap],
  ["/student/my-courses", BookOpen],
  ["/student/learning", BookOpen],
  ["/student/progress", TrendingUp],
  ["/student/personality-profile", Compass],
  ["/student/assessments", ClipboardList],
  ["/student/assignments", ClipboardList],
  ["/student/submissions", FileText],
  ["/student/quizzes", Puzzle],
  ["/student/certificates", Award],
  ["/student/applications", Inbox],
  ["/student/payment", CreditCard],
  ["/student/announcements", Bell],
  ["/student/forums", MessageSquare],
  ["/student/tickets", HelpCircle],
  ["/student/profile", User],
  ["/student/settings", Settings],
  ["/student/notifications", Bell],
];

export function navIconFor(href: string, label?: string): LucideIcon {
  if (label && ICON_BY_LABEL[label]) return ICON_BY_LABEL[label];

  const sorted = [...ICON_BY_PREFIX].sort((a, b) => b[0].length - a[0].length);
  for (const [prefix, icon] of sorted) {
    if (href === prefix || href.startsWith(`${prefix}/`)) return icon;
  }
  return Shield;
}
